# Generated by Django 3.2.16 on 2022-11-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submedias',
            old_name='mediaId',
            new_name='medias',
        ),
    ]
