# Generated by Django 3.2.16 on 2022-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_medias_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='mediaType',
            field=models.IntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Podcast')]),
        ),
    ]
