# Generated by Django 3.2.16 on 2022-10-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGenreMapping',
            fields=[
                ('mappingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('genreId', models.ForeignKey(db_column='genreId', on_delete=django.db.models.deletion.CASCADE, to='core.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('peopleId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('profileImagePath', models.CharField(blank=True, max_length=500, null=True)),
                ('twitterHandle', models.CharField(blank=True, max_length=500, null=True)),
                ('youTubleChannelUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(db_column='genreId', through='people.PeopleGenreMapping', to='core.Genres')),
            ],
        ),
        migrations.AddField(
            model_name='peoplegenremapping',
            name='peopleId',
            field=models.ForeignKey(db_column='peopleId', on_delete=django.db.models.deletion.CASCADE, to='people.peoples'),
        ),
        migrations.AddField(
            model_name='peoples',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
