# Generated by Django 3.2.16 on 2022-11-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='bannerImagePath',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peoples',
            name='bannerProfileImagePath',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        
    ]
