# Generated by Django 3.2.16 on 2022-10-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('tweetId', models.BigAutoField(primary_key=True, serialize=False)),
                ('externalTweetId', models.IntegerField()),
                ('tweet', models.CharField(blank=True, max_length=2000, null=True)),
                ('isRetweeted', models.BooleanField(default=False)),
                ('parentRetweetedId', models.IntegerField(blank=True, null=True)),
                ('tweetedBy', models.CharField(max_length=200)),
                ('tweetedOn', models.DateTimeField()),
                ('retweetsCount', models.IntegerField(default=0)),
                ('likesCount', models.IntegerField(default=0)),
                ('repliesCount', models.IntegerField(default=0)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('tweetedByPersonId', models.ForeignKey(db_column='tweetedByPersonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='people.peoples')),
            ],
        ),
    ]
