# Generated by Django 3.2.16 on 2022-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='externalTweetId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='parentRetweetedId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
